ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.sentry.SerializationKt.configureSerialization
      - io.sentry.RoutingKt.configureRouting
      - io.sentry.buddy.ConfigureFlowAnalysisKt.configureFlowAnalysis

flowAnalysis:
  dataDir: "data/flow-analysis"
