ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.sentry.buddy.SerializationKt.configureSerialization
      - io.sentry.buddy.flow.ConfigureFlowAnalysisKt.configureFlowAnalysis
      - io.sentry.buddy.healthcheck.ConfigureHealthCheckKt.configureHealthCheck
      - io.sentry.buddy.openurl.ConfigureOpenUrlKt.configureOpenUrl

flowAnalysis:
  dataDir: "data/flow-analysis"
