ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.sentry.buddy.SerializationKt.configureSerialization
      - io.sentry.buddy.endpoints.flow.ConfigureFlowAnalysisKt.configureFlowAnalysis
      - io.sentry.buddy.endpoints.openurl.ConfigureOpenUrlKt.configureOpenUrl

flowAnalysis:
  dataDir: "data/flow-analysis"
